# Generated by Django 4.1.4 on 2022-12-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='img',
            field=models.ImageField(default=1, upload_to='img/', verbose_name='items/static/img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
    ]
