# Generated by Django 4.1.4 on 2023-01-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_cardinfo_alter_items_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardInfo',
        ),
        migrations.AddField(
            model_name='items',
            name='color',
            field=models.TextField(blank=True, null=True, verbose_name='цвет'),
        ),
        migrations.AddField(
            model_name='items',
            name='linigMaterial',
            field=models.TextField(blank=True, null=True, verbose_name='Материал подкладки'),
        ),
        migrations.AddField(
            model_name='items',
            name='season',
            field=models.TextField(blank=True, null=True, verbose_name='сезон'),
        ),
        migrations.AddField(
            model_name='items',
            name='upperMaterial',
            field=models.TextField(blank=True, null=True, verbose_name='Метериал верха'),
        ),
    ]
