# Generated by Django 4.1.4 on 2023-01-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_delete_cardinfo_items_color_items_linigmaterial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
